### ISSUE TITLE
Add Aleph Objects 

### ISSUE THREAD

**Issue by kasbah** [opencompany/awesome-open-company#9]
Aleph Objects make [the Lulzbot 3D printer](https://www.lulzbot.com/) and have been [endorsed by the FSF](https://www.fsf.org/resources/hw/endorsement/aleph-objects).

**Comment by waldyrious** [comment]
Great suggestion, this is a no-brainer: their commitment to openness is showcased [all over](https://www.lulzbot.com/company) [the place](https://www.lulzbot.com/cloning-lulzbot-products). I suppose it would make more sense to link to the company website rather than the product, and in this case even the [home page](https://www.alephobjects.com) makes the libre aspect front and center, so it's unnecessary to seek a dedicated "openness" page. Alternatively, we could link to https://www.lulzbot.com/company, which would better fit the format of the other entries in the list, and is equally explicit about their stance on openness. What do you think?

**Comment by waldyrious** [comment]
@kasbah any thoughts about whether it fits better the pattern of rest of the list to link to https://www.alephobjects.com vs https://www.lulzbot.com/company?

**Comment by kasbah** [comment]
In my pull I went for alephobjects.com because it seemed like a better intro and maybe less confusing because people might think they clicked the wrong link at first.

**Comment by waldyrious** [comment]
Fair enough. Just making sure you took that decision explicitly. I don't have strong feelings either way, so I'll leave it be.

**Comment by nobodxbodon** [comment]
[Seems](https://github.com/opencompany/awesome-open-company/issues/61#issuecomment-1247144206) that Aleph Objects site was redirected to lulzbot before taken down. Shall we change it to "LulzBot (formerly Aleph Objects)"? 

I've not found a pledge page on the lulzbot site, while I suppose the statement "2011-2023 Fargo Additive Manufacturing Equipment 3D, LLC — Committed to Free Software and Open Source Hardware" counts?

**Comment by nobodxbodon** [comment]
According to [wiki](https://en.wikipedia.org/wiki/Aleph_Objects), Aleph Objects was acquired by the company that's running lulzbot.com now. 

> In November 2019, Aleph Objects announced that all of its assets have been acquired by Fargo Additive Manufacturing Equipment 3D (FAME 3D).[[17]](https://en.wikipedia.org/wiki/Aleph_Objects#cite_note-17)

As this page '[Choosing a Free License for Your 3D Project](https://lulzbot.com/learn/choosing-a-free-license-for-your-3d-project)' works as Openness Pledge, I'll update with the new company info.
